name: 64-bit Migration

on:
  push:
    branches: [master]

jobs:
  sync64:
    name: Synchronize 64-bit development with alpha development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: x64-dev
          # Fetch all history, so Git recognises the branches as related
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Merge in master
        run: |
          git fetch origin
          git merge origin/master --no-edit
          git push


